---
title: "Season's Informaiton and Post Injury Play Time For NFL Players"
author: 'Group D: Arthur, Donna, Kaitlyn, Michael'
date: "Friday, April 6, 2024"
output:
  pdf_document:
    fig_height: 3
    fig_width: 5
  word_document: default
---

```{r include=FALSE}
library(mosaic)
library(GGally)
require(tidyr)
library(tidyverse)
require(lattice)
library(gridExtra)
library(grid)
library(leaps)
options(scipen=5)
```

```{r include=FALSE}
# Some customization.  You can alter or delete as desired (if you know what you are doing).
# knitr settings to control how R chunks work.
require(knitr)
opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
trellis.par.set(theme=theme.mosaic())  
options(digits=5)
```


```{r, warning = FALSE, echo = FALSE, include=FALSE}
#getwd() in console to find the directory where the csv file is stored on your computer
#For your computer you need to change the path so you can reed the file
#alldata <- read.csv("/home/class26/FIRSTPARTOFEMAIL/ConcussionInjuries2012-2014.csv") 

#For Donna's computer
alldata <- read.csv("C:/Users/donna/OneDrive/Documents/STAT230/Stats230FinalProject/ConcussionInjuries2012-2014.csv") 

#For Kaitlyn's computer
#alldata <- read.csv("/home/class27/khuang27/StatsProjectFinal/ConcussionInjuries2012-2014.csv")

glimpse(alldata)
names(alldata)

#######################################################################################################

alldata <- filter(alldata, Reported.Injury.Type == "Concussion") ## filter so there's only concussions 
predictdata <-filter(alldata, Season == "2014/2015") ## data for the season we're predicting
alldata <- filter(alldata, Season != "2014/2015") ## our sample data

studyD <- rename(alldata, OppTeam = Opposing.Team, PostInjuryPlayTime = Play.Time.After.Injury, PreseasonInjury = Pre.Season.Injury., OnWinningTeam = Winning.Team., amtTimeInjured = Weeks.Injured, WeekOfInjury = Week.of.Injury, UnknownInjury = Unknown.Injury., ReportedTypeOfInjury = Reported.Injury.Type, AveragePreInjuryPlayTime = Average.Playtime.Before.Injury, TotalSnaps = Total.Snaps, amtGamesMissed = Games.Missed)
studyD <- studyD %>% 
  select(PostInjuryPlayTime, PreseasonInjury, Position, Season, amtGamesMissed, AveragePreInjuryPlayTime, WeekOfInjury )

studyD$PostIPT = parse_number(studyD$PostInjuryPlayTime)

studyD$PreIPT = parse_number(studyD$AveragePreInjuryPlayTime)

#######################################################################################################
## this re-categorizes position to offense and defense
studydata <- studyD %>% 
    mutate(Position = case_when(
    Position %in% c("Defensive End", "Defensive Tackle", "Safety", "Comerback" ) ~ "defense",
    Position %in% c("Long Snapper", "Wide Receiver", "Tight End", "Linebacker", "Quarterback", "Center", "Guard", "Full Back", "Running Back", "Offensive Tackle") ~ "offense"))
```
*Project Question/Aim*

*Research Question*

*Variables*

*Step 1: Univariate analysis - descriptive stats/plots for each variable*
```{r}
##PostIPT RESPONSE VARIABLE
favstats(~PostIPT, data = studydata)
gf_dhistogram(~PostIPT, data = studydata)%>%
  gf_dens()

```
```{r}
##EXPLANATORY VARIABLES

## quantitative

m1 <- gf_histogram(~amtGamesMissed, data = studydata)

m2 <- gf_dhistogram(~PreIPT, data = studydata) %>%
  gf_dens()

m3 <- gf_histogram(~WeekOfInjury, data = studydata, main = "Distribution of Week of Injury")


grid.arrange(m1, m2, m3, ncol = 3 ,heights = .5) 



##qualitative
m4 <- gf_bar(~ PreseasonInjury, data = studydata, fill = c("darkred", "forestgreen"), main = "Number of Preseason Injuries")

tally(~ Position, data = studydata)

m5 <- gf_bar(~Season, data = studydata)

grid.arrange(m4, m5, ncol = 2 ,heights = .5) 

```


*Step 2: Compare variables in Bivariate Manner -  Stats, Plots, and Compare*

```{r}
studydata1 <- select(studydata, "PostIPT" , "amtGamesMissed", "PreIPT", "WeekOfInjury", "PreseasonInjury", "Position", "Season")
##ggpairs(studydata1)

gf_point(PostIPT ~ amtGamesMissed, data = studydata)

```


*Step 3: Model Building and Variable Selection - Choosing Variables, Checking/Evaluating Fit, and Final Model Criteria*